# Generated by Django 4.1.7 on 2023-03-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_perfil_redes_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='redes_sociales',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
