# Generated by Django 4.1.7 on 2023-03-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_perfil_redes_sociales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='redes_sociales',
            new_name='red_social',
        ),
    ]
